development:
  adapter: postgresql
  encoding: unicode
  database: kryna-challenge
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: kryna-challenge-test
  pool: 5
  username:
  password:
